import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.sun.jna.Structure;

/**
		 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
		 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
		 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
		 */
		public class eventStruct extends Structure {
			/// idle link list
			public byte nextRec;
			/// EPIC command
			public byte cmd;
			/// C type : unsigned char[16]
			public byte[] data = new byte[16];
			public eventStruct() {
				super();
				initFieldOrder();
			}
			protected void initFieldOrder() {
			//	setFieldOrder(new String[]{"nextRec", "cmd", "data"});
				Arrays.asList(new String[] { "nextRec", "cmd", "data" });
			}
			/**
			 * @param nextRec idle link list<br>
			 * @param cmd EPIC command<br>
			 * @param data C type : unsigned char[16]
			 */
			public eventStruct(byte nextRec, byte cmd, byte data[]) {
				super();
				this.nextRec = nextRec;
				this.cmd = cmd;
				if (data.length != this.data.length) 
					throw new IllegalArgumentException("Wrong array size !");
				this.data = data;
				initFieldOrder();
			}
			public  class ByReference extends eventStruct implements Structure.ByReference {

				@Override
				protected List getFieldOrder() {
					// TODO Auto-generated method stub
					return Arrays.asList(new String[] { "nextRec", "cmd", "data" });
				}
				
			};
			public class ByValue extends eventStruct implements Structure.ByValue {

				@Override
				protected List getFieldOrder() {
					// TODO Auto-generated method stub
					return Arrays.asList(new String[] { "nextRec", "cmd", "data" });
				}
				
			}
			@Override
			protected List getFieldOrder() {
				// TODO Auto-generated method stub
				return Arrays.asList(new String[] { "nextRec", "cmd", "data" });
			};
		}

